# Generated by Django 4.1.3 on 2023-10-29 15:52


from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name of the supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercardiscount',
            unique_together={('name', 'supplier')},
        ),
    ]
