# Generated by Django 4.1.3 on 2023-10-30 20:43


import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('showroom', '0003_alter_showroomcardiscount_unique_together_and_more'),
        ('core', '0001_initial'),
        ('supplier', '0002_alter_suppliermodel_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliercar',
            options={
                'ordering': ['price'],
                'verbose_name': 'Supplier car',
                'verbose_name_plural': 'Supplier cars',
            },
        ),
        migrations.AlterUniqueTogether(
            name='suppliercardiscount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='showrooms',
            field=models.ManyToManyField(
                related_name='current_suppliers',
                related_query_name='current_suppliers',
                to='showroom.showroommodel',
                verbose_name='current showroomss of the supplier',
            ),
        ),
        migrations.AlterField(
            model_name='supplierhistory',
            name='car',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='supplier_history',
                related_query_name='supplier_history',
                to='core.carmodel',
                verbose_name='car',
            ),
        ),
        migrations.AlterField(
            model_name='supplierhistory',
            name='showroom',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='supplier_history',
                related_query_name='supplier_history',
                to='showroom.showroommodel',
                verbose_name='showroom',
            ),
        ),
    ]
