version: '3.7'
services:
  web:
    build:
      context: ./car_salon_activities
      dockerfile: Dockerfile
    container_name: car-salon-container
    env_file:
      - ./car_salon_activities/.env
    ports:
      - 8000:${DJANGO_SERVER_PORT}
    entrypoint:
      - ./django-entrypoint.sh
    restart: always
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.4-alpine
    volumes:
      - ./car_salon_activities/data/db:/var/lib/postgresql/data
    env_file:
      - ./car_salon_activities/.env
    ports:
      - 5432:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always