# Generated by Django 4.2.6 on 2023-10-24 18:20


import django.core.validators
from django.db import models, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                (
                    'brand',
                    models.CharField(
                        choices=[
                            (None, 'Choose brand of the car.'),
                            ('audi', 'Audi'),
                            ('bmw', 'BMW'),
                            ('tesla', 'Tesla'),
                        ],
                        verbose_name='brand of the car',
                    ),
                ),
                (
                    'transmission_type',
                    models.CharField(
                        choices=[
                            (None, 'Choose transmission type of the car.'),
                            ('manual', 'Manual'),
                            ('auto', 'Automatic'),
                        ],
                        verbose_name='transmission type of the car',
                    ),
                ),
                (
                    'creation_year',
                    models.PositiveIntegerField(verbose_name='creation year of the car'),
                ),
                (
                    'miliage',
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name='miliage of the car',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'db_table': 'Car',
            },
        ),
    ]
