# Generated by Django 4.1.3 on 2023-10-26 21:05


import django.core.validators
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(
                choices=[('audi', 'Audi'), ('bmw', 'BMW'), ('tesla', 'Tesla')],
                max_length=50,
                verbose_name='brand of the car',
            ),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='creation_year',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1900)],
                verbose_name='creation year of the car',
            ),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmission_type',
            field=models.CharField(
                choices=[('manual', 'Manual'), ('auto', 'Automatic')],
                max_length=50,
                verbose_name='transmission type of the car',
            ),
        ),
    ]
