apiVersion: v1
kind: Service
metadata:
  name: service-gunicorn
  namespace: production
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: gunicorn
    rel: stable