apiVersion: v1
kind: Service
metadata:
  name: service-database-public
  namespace: production
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: database-postgres
    rel: stable