apiVersion: v1
kind: Service
metadata:
  name: service-rabbitmq-management
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - name: management
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
    rel: stable