apiVersion: v1
kind: Service
metadata:
  name: service-database-headless
  namespace: production
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5432
  selector:
    app: database-postgres
    rel: stable