apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - name: tls
    port: 1337
    targetPort: 443
  selector:
    app: nginx
    rel: stable