# Generated by Django 4.1.3 on 2023-10-26 21:33


import django.core.validators
import django_countries.fields
import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('supplier', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=50, verbose_name='name of the showroom')),
                (
                    'creation_year',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name='creation year of the showroom',
                    ),
                ),
                (
                    'balance',
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name='balance',
                    ),
                ),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('charts', models.JSONField(verbose_name='charts of appropriate cars')),
                (
                    'number_of_sales',
                    models.PositiveIntegerField(
                        default=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='number of sales after which discount is provided',
                    ),
                ),
                (
                    'discount_for_unique_customers',
                    models.DecimalField(
                        decimal_places=2,
                        default=0.2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(0.5),
                        ],
                        verbose_name='discount precent for unique customers',
                    ),
                ),
                (
                    'appropriate_cars',
                    models.ManyToManyField(
                        related_name='showrooms',
                        related_query_name='showrooms',
                        to='core.carmodel',
                        verbose_name='appropriate cars for the showroom',
                    ),
                ),
                (
                    'current_suppliers',
                    models.ManyToManyField(
                        related_name='showrooms',
                        related_query_name='showrooms',
                        to='supplier.suppliermodel',
                        verbose_name='current suppliers of the showroom',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Showroom',
                'verbose_name_plural': 'Showrooms',
                'db_table': 'Showroom',
            },
        ),
        migrations.CreateModel(
            name='ShowroomHistory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('car', models.CharField(max_length=50, verbose_name='car')),
                (
                    'sale_price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name='sale price',
                    ),
                ),
                ('customer', models.CharField(max_length=50, verbose_name='customer')),
                (
                    'showroom',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='history',
                        related_query_name='history',
                        to='showroom.showroommodel',
                        verbose_name='showroom which owns history entry',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Showroom history entry',
                'verbose_name_plural': 'Showroom history',
                'db_table': 'ShowroomHistory',
            },
        ),
        migrations.CreateModel(
            name='ShowroomCarDiscount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=50, verbose_name='discount name')),
                ('description', models.TextField(verbose_name='discount description')),
                (
                    'precent',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(0.5),
                        ],
                        verbose_name='discount precent',
                    ),
                ),
                ('start_date', models.DateTimeField(verbose_name='start date of the discount')),
                ('finish_date', models.DateTimeField(verbose_name='finish date of the discount')),
                (
                    'cars',
                    models.ManyToManyField(
                        related_name='showroom_discounts',
                        related_query_name='showroom_discounts',
                        to='core.carmodel',
                        verbose_name='cars with discounts',
                    ),
                ),
                (
                    'showroom',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='discounts',
                        related_query_name='discounts',
                        to='showroom.showroommodel',
                        verbose_name='showroom which provides discount',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Showroom discount',
                'verbose_name_plural': 'Showroom discounts.',
                'db_table': 'ShowroomDiscount',
            },
        ),
        migrations.CreateModel(
            name='ShowroomCar',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name='price of the car',
                    ),
                ),
                (
                    'car',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='showroom_cars',
                        related_query_name='showroom_cars',
                        to='core.carmodel',
                        verbose_name='showroom car',
                    ),
                ),
                (
                    'showroom',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cars',
                        related_query_name='cars',
                        to='showroom.showroommodel',
                        verbose_name='showroom that owns cars',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='cars',
                        related_query_name='cars',
                        to='customer.customermodel',
                        verbose_name='user who has bought the car',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Showroom car',
                'verbose_name_plural': 'Showroom cars',
                'db_table': 'ShowroomCar',
            },
        ),
    ]
