# Generated by Django 4.2.6 on 2023-10-24 18:20


import django.core.validators
import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('jauth', '0003_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                (
                    'balance',
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name='balance',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='jauth.user',
                        verbose_name='user instance',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('car', models.CharField(verbose_name='car')),
                (
                    'purchase_price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name='purchase price',
                    ),
                ),
                ('showroom', models.CharField(verbose_name='showroom')),
                (
                    'customer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='history',
                        related_query_name='history',
                        to='customer.customermodel',
                        verbose_name='customer which owns history entry',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Customer history entry',
                'verbose_name_plural': 'Customer history',
                'db_table': 'CustomerHistory',
            },
        ),
    ]
