# Generated by Django 4.1.3 on 2023-10-31 21:16


import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
        ('customer', '0003_alter_customeroffer_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerhistory',
            name='car',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='customer_cars',
                related_query_name='customer_cars',
                to='core.carmodel',
                verbose_name='customer car',
            ),
        ),
    ]
