# Generated by Django 4.1.3 on 2023-10-29 15:52


from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroommodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name of the showroom'),
        ),
        migrations.AlterUniqueTogether(
            name='showroomcardiscount',
            unique_together={('name', 'showroom')},
        ),
    ]
