# Generated by Django 4.1.3 on 2023-10-30 20:43


import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
        ('customer', '0001_initial'),
        ('showroom', '0002_alter_showroommodel_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showroomcardiscount',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='showroommodel',
            name='current_suppliers',
        ),
        migrations.AlterField(
            model_name='showroomhistory',
            name='car',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='showroom_history',
                related_query_name='showroom_history',
                to='core.carmodel',
                verbose_name='car',
            ),
        ),
        migrations.AlterField(
            model_name='showroomhistory',
            name='customer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='showroom_history',
                related_query_name='showroom_history',
                to='customer.customermodel',
                verbose_name='customer',
            ),
        ),
    ]
