# Generated by Django 4.1.3 on 2023-10-26 21:13


import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_alter_carmodel_brand_alter_carmodel_creation_year_and_more'),
        (
            'showroom',
            '0002_rename_discount_for_unique_castomers_showroommodel_discount_for_unique_customers_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroomcar',
            name='discount',
        ),
        migrations.AddField(
            model_name='showroomcar',
            name='car',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='showroom_cars',
                related_query_name='showroom_cars',
                to='core.carmodel',
                verbose_name='showroom car',
            ),
        ),
        migrations.AddField(
            model_name='showroomcardiscount',
            name='cars',
            field=models.ManyToManyField(
                related_name='showroom_discounts',
                related_query_name='showroom_discounts',
                to='core.carmodel',
                verbose_name='cars with discounts',
            ),
        ),
    ]
