# Generated by Django 4.1.3 on 2023-10-31 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('showroom', '0003_alter_showroomcardiscount_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showroomcar',
            options={
                'ordering': ['price'],
                'verbose_name': 'Showroom car',
                'verbose_name_plural': 'Showroom cars',
            },
        ),
    ]
