# Generated by Django 4.1.3 on 2023-10-26 21:14


import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_alter_carmodel_brand_alter_carmodel_creation_year_and_more'),
        ('showroom', '0003_remove_showroomcar_discount_showroomcar_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomcar',
            name='car',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='showroom_cars',
                related_query_name='showroom_cars',
                to='core.carmodel',
                verbose_name='showroom car',
            ),
        ),
    ]
