version: '3.7'

services:
  postgres:
    image: postgres:14.4-alpine
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=4GB"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "wal_writer_delay=400ms"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "autovacuum_naptime=5min"
      - "-c"
      - "autovacuum_max_workers=8"
    hostname: postgres
    ports:
      - 5432:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
