version: '3.7'

services:
  postgres:
    image: postgres:14.4-alpine
    hostname: postgres
    ports:
      - 5432:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
