# Generated by Django 4.2.6 on 2023-10-12 17:20


from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
    ]
