# Generated by Django 4.2.6 on 2023-10-13 08:29


from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jauth', '0002_user_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is verified'),
        ),
    ]
