apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-production
  namespace: production
spec:
  limits:
  - type: PersistentVolumeClaim
    min:
      storage: 1Gi
    max:
      storage: 2Gi