apiVersion: v1
kind: Secret
metadata:
  name: secret-production
  namespace: production
data:
  ALLOWED_HOSTS: bG9jYWxob3N0LA==
  DB_NAME: Q2FyU2Fsb25Qcm9qZWN0
  DB_PASSWORD: QW5uaWVsZW8x
  DB_PORT: NTQzMg==
  DB_USER: VHdlbHZl
  DEFAULT_FROM_EMAIL: aWx5YS5zYXZpbi5yZXNlcnZlQGdtYWlsLmNvbQ==
  DJANGO_GUNICORN_HOST: MC4wLjAuMA==
  DJANGO_GUNICORN_PORT: NDQz
  DJANGO_NGINX_PORT: NDQz
  EMAIL_DEF_USER: aWx5YS5zYXZpbkBweW5lc3QuaW8=
  EMAIL_HOST: c210cC5nbWFpbC5jb20=
  EMAIL_HOST_PASSWORD: J29reGUgbG14aCB1YndzIHZ3b3Qn
  EMAIL_HOST_USER: aWx5YS5zYXZpbi5yZXNlcnZlQGdtYWlsLmNvbQ==
  EMAIL_PORT: NTg3
  FLOWER_PORT: NTU1NQ==
  FRONTEND_URL: Jy8n
  MASTER_DB_NAME: bWFzdGVy
  RABBITMQ_PASS: QW5uaWVsZW8x
  RABBITMQ_USER: VHdlbHZl
  REDIS_DB_NUMBER: MAo=
  REDIS_PASSWORD: QW5uaWVsZW8x
  SECRET_KEY: Jyt6KileaSg2Y2EqdSskQCp5cl50ayp2Mj1fc2JtZzdlJTkqdXF6PSlxNjdzMTdvKEBrJw==
  SENTRY_DNS: aHR0cHM6Ly8wMTlmMmY4YjE1N2JjYjdhNzg2MGZkM2UzYmZlYzg1YkBvNDUwNjA2NTUzODM4Mzg3Mi5pbmdlc3Quc2VudHJ5LmlvLzQ1MDYwNjU1NDAyMTg4ODA=
type: Opaque