version: '3.7'

services:
  postgres:
    env_file:
      - ./env/production/.env.prod.postgres
    volumes:
      - ./car_salon_activities/data/postgres:/var/lib/postgresql/data
    networks:
      back-prod:
        ipv4_address: 172.168.10.10