version: '3.7'

services:
  rabbitmq:
    env_file:
      - ./env/production/.env.prod.rabbitmq
    volumes:
      - ./src/data/prod/rabbitmq:/var/lib/rabbitmq
    networks:
      back-prod:
        ipv4_address: 172.168.10.10