"""
Django settings for car_salon_activities project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""


import os
from typing import Optional
from pathlib import Path


# -------------------------- MAIN SETTINGS ------------------------------------

BASE_DIR: Path = Path(__file__).resolve().parent.parent

SECRET_KEY: Optional[str] = os.getenv('SECRET_KEY')

DEBUG: Optional[str] = os.getenv('DEBUG')

ALLOWED_HOSTS: Optional[list] = os.getenv('ALLOWED_HOSTS', 'localhost').split(',')

DEFAULT_CHARSET: str = 'utf8'

ROOT_URLCONF: str = 'car_salon_activities.urls'

AUTH_USER_MODEL: str = 'jauth.User'

# -------------------------- INSTALLED APPS -----------------------------------

INSTALLED_APPS: list = [
    'jauth.apps.JauthConfig',
    'salon.apps.SalonConfig',
    'rest_framework',
]

# -------------------------- MIDDLEWARES --------------------------------------

MIDDLEWARE: list = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---------------------------- DATABASES --------------------------------------

DATABASES: dict = {
    'master': {
        'ENGINE': os.getenv('POSTGRES_ENGINE'),
        'NAME': os.getenv('POSTGRES_DB'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'CONN_MAX_AGE': int(os.getenv('CONN_MAX_AGE', '0')),
    },
    'default': {
        'ENGINE': os.getenv('POSTGRES_ENGINE'),
        'NAME': os.getenv('POSTGRES_DB'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'CONN_MAX_AGE': int(os.getenv('CONN_MAX_AGE', '0')),
    },
}

# ------------------------- LANGUAGE SETTINGS ---------------------------------

LANGUAGE_CODE: str = 'en-us'

USE_I18N: bool = False

USE_L10N: bool = False

TIME_ZONE: str = 'UTC'

USE_TZ: bool = True

# --------------------------- DRF SETTINGS ------------------------------------

REST_FRAMEWORK: dict = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'jauth.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'UNAUTHENTICATED_USER': None,
    'UNAUTHENTICATED_TOKEN': None,
    'UNICODE_JSON': False,
    'COMPACT_JSON': False,
    'STRICT_JSON': True,
}

# -------------------------- JWT SETTINGS -------------------------------------

JWT_TOKEN: dict = {
    'ACCESS_TOKEN_LIFETIME_MINUTES': 15,
    'REFRESH_TOKEN_LIFETIME_DAYS': 30,
    'TOKEN_TYPE': 'Bearer',
    'ENCODE_ALG': 'HS256',
    'DECODE_ALGS': ['HS256'],
    'HEADER_NAME': 'HTTP_AUTHORIZATION',
}

# -------------------------- OTHER SETTINGS -----------------------------------

WSGI_APPLICATION: str = 'car_salon_activities.wsgi.application'

DEFAULT_AUTO_FIELD: str = 'django.db.models.BigAutoField'
