# Generated by Django 4.1.3 on 2023-10-26 21:33


import django.core.validators
from django.db import models, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                (
                    'brand',
                    models.CharField(
                        choices=[('audi', 'Audi'), ('bmw', 'BMW'), ('tesla', 'Tesla')],
                        max_length=50,
                        verbose_name='brand of the car',
                    ),
                ),
                (
                    'transmission_type',
                    models.CharField(
                        choices=[('manual', 'Manual'), ('auto', 'Automatic')],
                        max_length=50,
                        verbose_name='transmission type of the car',
                    ),
                ),
                (
                    'creation_year',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name='creation year of the car',
                    ),
                ),
                (
                    'miliage',
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name='miliage of the car',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'db_table': 'Car',
            },
        ),
    ]
