# Generated by Django 4.2.5 on 2023-10-05 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(8)],
                        verbose_name='username',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        db_index=True,
                        max_length=320,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name='email',
                    ),
                ),
                (
                    'password',
                    models.CharField(
                        max_length=128,
                        validators=[django.core.validators.MinLengthValidator(8)],
                        verbose_name='password',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name='first name'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name='last name'
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
                ),
                (
                    'last_login',
                    models.DateTimeField(blank=True, null=True, verbose_name='last login'),
                ),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
        ),
    ]
