# Generated by Django 4.1.3 on 2023-10-31 19:51


import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
        ('customer', '0002_customeroffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeroffer',
            name='car',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='customer_offers',
                related_query_name='customer offers',
                to='core.carmodel',
                verbose_name='car specified in offer',
            ),
            preserve_default=False,
        ),
    ]
