# Generated by Django 4.1.3 on 2023-10-26 21:06


from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliermodel',
            old_name='year',
            new_name='creation_year',
        ),
        migrations.RenameField(
            model_name='suppliermodel',
            old_name='discount_for_unique_castomers',
            new_name='discount_for_unique_customers',
        ),
        migrations.AlterField(
            model_name='suppliercardiscount',
            name='name',
            field=models.CharField(max_length=50, verbose_name='discount name'),
        ),
        migrations.AlterField(
            model_name='supplierhistory',
            name='car',
            field=models.CharField(max_length=50, verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='supplierhistory',
            name='showroom',
            field=models.CharField(max_length=50, verbose_name='showroom'),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name of the supplier'),
        ),
    ]
