# Generated by Django 4.1.3 on 2023-10-26 21:15


import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_alter_carmodel_brand_alter_carmodel_creation_year_and_more'),
        ('supplier', '0003_remove_suppliercar_discount_suppliercar_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercar',
            name='car',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='supplier_cars',
                related_query_name='supplier_cars',
                to='core.carmodel',
                verbose_name='supplier car',
            ),
        ),
    ]
