# 1 layer
FROM nginx:alpine
LABEL author="ilya.savin@pynest.io"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 2 layer
RUN apk update && apk add bash curl postgresql-dev gcc g++ python3-dev musl-dev py3-pip && pip install pipenv

# 3 layer
WORKDIR /code
COPY Pipfile Pipfile.lock ./

# 4 layer
RUN pipenv install --system --deploy --ignore-pipfile

# 5 layer
COPY . ./

# 6 layer
RUN sphinx-build -M html ./docs /usr/share/nginx/
EXPOSE 7777