[tool.isort]
line_length = 100
lines_before_imports = 2
lines_after_imports = 2
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
treat_all_comments_as_code = "True"
length_sort = "True"
lines_between_sections = 0

[tool.flake8]
max-line-length = 100
exclude = ['migrations', 'data']
ignore = ['E203', 'E266', 'E704', 'W503', 'B905', 'B907']
max-complexity = 18
select = ['B', 'C', 'E', 'F', 'W', 'T4', 'B9']

[tool.mypy]
ignore_missing_imports = "True"
disallow_untyped_defs = "True"
check_untyped_defs = "True"
warn_redundant_casts = "True"
no_implicit_optional = "True"
strict_optional = "True"
exclude = '''(?x)(
    ^data/$
    | migrations/$
)'''

[tool.black]
line-length = 100
skip-string-normalization = 1
preview = 1
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | data
)/
'''
