name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./car_salon_activities

    steps:
      - name: clone github repository
        uses: actions/checkout@v3

      - name: install python3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: create venv and install dependencies
        run: pipenv install --system --deploy --ignore-pipfile

      - name: run flake8
        run: pipenv run flake8 .

      - name: run black
        uses: psf/black@stable
        with:
          version: "23.9.1"
          src: "./car_salon_activities"
          options: "--check --verbose"

      - name: run isort
        uses: isort/isort-action@master
        with:
          isortVersion: "5.12.0"
          sortPaths: "./car_salon_activities"
          configuration: "--check-only --verbose"

      - name: run mypy
        run: pipenv run mypy .