name: CI

on: [push, pull_request]

jobs:
  static:
    runs-on: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: clone github repository
        uses: actions/checkout@v3

      - name: install python3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: install pipenv
        run: pip install pipenv

      - name: create venv and install dependencies
        run: pipenv install --categories=test-packages --system --deploy --ignore-pipfile

      - name: run flake8
        run: pipenv run flake8 .

      - name: run black
        run: pipenv run black --check .

      - name: run isort
        run: pipenv run isort --check-only .

      - name: run mypy
        run: pipenv run mypy .

      - name: run unit tests
        run: pipenv run pytest tests/unit/

  it:
    runs-on: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./

    steps:
      - name: clone github repository
        uses: actions/checkout@v3

      - name: create envs files
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "${{ secrets.ENV_FILE_COMPOSE }}" > ./env/tests/.env.tests.compose
          echo "${{ secrets.ENV_FILE_DJANGO }}" > ./env/tests/.env.tests.django
          echo "${{ secrets.ENV_FILE_POSTGRES }}" > ./env/tests/.env.tests.postgres
          echo "${{ secrets.ENV_FILE_RABBITMQ }}" > ./env/tests/.env.tests.rabbitmq
          echo "${{ secrets.ENV_FILE_REDIS }}" > ./env/tests/.env.tests.redis

      - name: run integration tests
        run: make itests