name: CI

on: [push]

jobs:
  ci:
    runs-on: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./car_salon_activities

    steps:
      - name: clone github repository
        uses: actions/checkout@master

      - name: install python3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: install pipenv
        run: pip install pipenv

      - name: create venv and install dependencies
        run: pipenv install --system --deploy --ignore-pipfile

      - name: run flake8
        run: run flake8 .

      - name: run black
        run: black --check .

      - name: run isort
        run: isort --check-only .

      - name: run mypy
        run: mypy .