apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-celery
  namespace: production
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: celery
      rel: stable
  template:
    metadata:
      name: celery-pod
      labels:
        app: celery
        rel: stable
    spec:
      serviceAccountName: service-account-production
      containers:
      - name: celery
        image: twelvecloud/car.showroom:django-production
        command: ["./celery-entrypoint.sh"]
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: secret-django-production
        - configMapRef:
            name: configmap-django
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec celery -A config inspect ping --destination worker1@$HOSTNAME
          initialDelaySeconds: 3
          successThreshold: 1
          failureThreshold: 18
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec celery -A config inspect ping --destination worker1@$HOSTNAME
          initialDelaySeconds: 5
          successThreshold: 1
          failureThreshold: 6
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec celery -A config inspect ping --destination worker1@$HOSTNAME
          initialDelaySeconds: 30
          successThreshold: 1
          failureThreshold: 6
          periodSeconds: 10
          timeoutSeconds: 5
      - name: beat
        image: twelvecloud/car.showroom:django-production
        command: ["./beat-entrypoint.sh"]
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: secret-django-production
        - configMapRef:
            name: configmap-django
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pgrep celery
          initialDelaySeconds: 3
          successThreshold: 1
          failureThreshold: 18
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pgrep celery
          initialDelaySeconds: 5
          successThreshold: 1
          failureThreshold: 6
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pgrep celery
          initialDelaySeconds: 30
          successThreshold: 1
          failureThreshold: 6
          periodSeconds: 10
          timeoutSeconds: 5
      - name: flower
        image: twelvecloud/car.showroom:django-production
        command: ["./flower-entrypoint.sh"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5555
          protocol: TCP
        envFrom:
        - secretRef:
            name: secret-django-production
        - configMapRef:
            name: configmap-django
        startupProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 3
          successThreshold: 1
          failureThreshold: 18
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 5
          successThreshold: 1
          failureThreshold: 6
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 30
          successThreshold: 1
          failureThreshold: 6
          periodSeconds: 10
          timeoutSeconds: 5
      restartPolicy: Always