apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  namespace: production
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
      rel: stable
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        rel: stable
    spec:
      serviceAccountName: service-account-production
      containers:
      - name: nginx
        image: twelvecloud/car.showroom:nginx-production
        imagePullPolicy: Always
        ports:
        - name: https
          containerPort: 443
          protocol: TCP
        envFrom:
        - secretRef:
            name: secret-django-production
        - configMapRef:
            name: configmap-django
        volumeMounts:
        - name: certificate
          mountPath: /etc/nginx/certs/
          readOnly: true
        startupProbe:
          httpGet:
            path: /api/schema/swagger/
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 20
          successThreshold: 1
          failureThreshold: 18
          periodSeconds: 10
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/schema/swagger/
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 60
          successThreshold: 1
          failureThreshold: 6
          periodSeconds: 10
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /api/schema/swagger/
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 120
          successThreshold: 1
          failureThreshold: 6
          periodSeconds: 10
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 300Mi
      volumes:
      - name: certificate
        secret:
          secretName: certificate-https
      restartPolicy: Always