apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-redis
  namespace: production
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
      rel: stable
  template:
    metadata:
      name: redis-pod
      labels:
        app: redis
        rel: stable
    spec:
      serviceAccountName: service-account-production
      containers:
      - name: redis
        image: redis:7.2.1-alpine3.18
        command: ["redis-server"]
        args: ["--requirepass",  "Annieleo1"]
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          protocol: TCP
        envFrom:
          - secretRef:
              name: secret-redis-production
        volumeMounts:
        - name: data
          mountPath: /root/redis
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec redis-cli ping
          initialDelaySeconds: 3
          successThreshold: 1
          failureThreshold: 18
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec redis-cli ping
          initialDelaySeconds: 5
          successThreshold: 1
          failureThreshold: 6
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec redis-cli ping
          initialDelaySeconds: 30
          successThreshold: 1
          failureThreshold: 6
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: data
        hostPath:
          path: /k8s/data/prod/redis
      restartPolicy: Always